# Generated by Django 5.0.4 on 2024-05-02 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('image_type', models.CharField(choices=[('Lidar', 'Lidar'), ('Multispectral', 'Multispectral'), ('NDVI', 'NDVI'), ('DEM', 'DEM')])),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images_to/')),
            ],
        ),
    ]
