# Generated by Django 5.0.4 on 2024-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='images',
            name='description',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='description_Lidar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='images',
            name='description_NDVI',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='images',
            name='description_multi_spect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image_Lidar',
            field=models.ImageField(blank=True, upload_to='images_to/'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_NDVI',
            field=models.ImageField(blank=True, upload_to='images_to/'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_multi_spect',
            field=models.ImageField(blank=True, upload_to='images_to/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('Multispectral', 'Multispectral'), ('NDVI', 'NDVI'), ('Lidar', 'Lidar')]),
        ),
    ]
