# Generated by Django 5.0.4 on 2024-05-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='description_Lidar',
        ),
        migrations.RemoveField(
            model_name='images',
            name='description_NDVI',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_Lidar',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_NDVI',
        ),
    ]
