# Generated by Django 5.0.6 on 2024-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_images_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('RGB Orthomosaic', 'RGB Orthomosaic'), ('NDVI', 'NDVI'), ('NDVI Change', 'NDVI Change'), ('Change Detection', 'Change Detection'), ('DSM', 'DSM'), ('DTM', 'DTM'), ('CHM', 'CHM'), ('Lidar', 'Lidar'), ('sfm', 'sfm'), ('DEM_DSM', 'DEM_DSM'), ('Diff_DEM_DSM_Volume', 'Diff_DEM_DSM_Volume'), ('Hillshade_slope', 'Hillshade_slope')], max_length=20),
        ),
    ]
