# Generated by Django 5.0.4 on 2024-06-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_images_description_lidar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_multi_spect',
        ),
    ]
