# Generated by Django 5.0.4 on 2024-06-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_images_image_multi_spect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('RGB Orthomosaic', 'RGB Orthomosaic'), ('Multispectral', 'Multispectral'), ('NDVI', 'NDVI'), ('Lidar', 'Lidar')]),
        ),
    ]
