# Generated by Django 5.0.4 on 2024-06-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_images_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('RGB Orthomosaic', 'RGB Orthomosaic'), ('Multispectral', 'Multispectral'), ('NDVI', 'NDVI'), ('Lidar', 'Lidar'), ('Change Detection', 'Change Detection')]),
        ),
    ]
