# Generated by Django 5.0.6 on 2024-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_images_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('RGB Orthomosaic', 'RGB Orthomosaic'), ('Multispectral', 'Multispectral'), ('NDVI', 'NDVI'), ('Lidar', 'Lidar'), ('Change Detection', 'Change Detection'), ('sfm', 'sfm')], max_length=20),
        ),
    ]
