# Generated by Django 5.0.6 on 2024-06-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_images_image_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='description_multi_spect',
            new_name='description',
        ),
    ]
