# Generated by Django 5.0.4 on 2024-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_rename_description_multi_spect_images_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('RGB Orthomosaic', 'RGB Orthomosaic'), ('Multispectral', 'Multispectral'), ('NDVI', 'NDVI'), ('Lidar', 'Lidar'), ('Change Detection', 'Change Detection'), ('sfm', 'sfm'), ('DEM_DSM', 'DEM_DSM'), ('Diff_DEM_DSM_Volume', 'Diff_DEM_DSM_Volume')], max_length=20),
        ),
    ]
